const cities = [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruppur",
    "Salem",
    "Tiruchirappalli",
    "Erode",
    "Tirunelveli",
    "Vellore",
    "Thoothukudi",]



const cityAreas = {
    Chennai: [
        "Anna Nagar",
        "Adyar",
        "Mylapore",
        "T Nagar",
        "Egmore",
        "Guindy",
        "Velachery",
        "OMR",
        "Porur",
        "Karapakkam",
        "Valasaravakkam",
        "Perambur",
        "Kodungaiyur",
        "Ambattur",
        "Thirumangalam",
        "Madipakkam",
        "Nungambakkam",
        "Sholinganallur",
        "K K Nagar",
        "Alandur",
        "Tambaram",
        "Chromepet",
        "Perungudi",
        "Porur",
        "Thiruvanmiyur",
        "Medavakkam",
        "Iyyappanthangal",
        "Pallikaranai",
        "Puzhal",
    ],
    Coimbatore: [
        "R S Puram",
        "Gandhipuram",
        "Saibaba Colony",
        "Race Course",
        "Podanur",
        "Singanallur",
        "Saravanampatti",
        "Peelamedu",
        "Valankulam",
        "Ukkadam",
        "Avinashi Road",
        "Sathyamangalam Road",
        "Mettupalayam Road",
        "Pollachi Road",
        "Tirupur Road",
        "Karur Road",
        "Erode Road",
        "Dindigul Road",
    ],
    Madurai: [
        "Madurai Central",
        "Melur",
        "Thirumangalam",
        "Avaniapuram",
        "KK Nagar",
        "K Pudur",
        "Goripalayam",
        "Mattuthavani",
        "Tiruparankundram",
        "Melur",
        "Tirumangalam Taluk",
        "Madurai North",
        "Madurai South",
        "Madurai West",
        "Madurai East",
    ],
    Tiruppur: [
        "Tiruppur Town",
        "Muthu",
        "Avinashi",
        "Pallamedu",
        "Perumanur",
        "Kunnathur",
        "Tiruchendur",
        "Srivilliputhur",
        "Sankarankovil",
        "Papanasam",
        "Pallamdal Taluk",
        "Tiruppur North",
        "Tiruppur South",
    ],
    Salem: [
        "Salem City",
        "Yercaud",
        "Mettur",
        "Rasipuram",
        "Namakkal",
        "Salem North",
        "Salem South",
        "Omalur",
        "Attur",
        "Salem West",
        "Salem East",
        "Krishnagiri",
        "Dharmapuri",
    ],
    Tiruchirappalli: [
        "Tiruchirappalli City",
        "Srirangam",
        "Thirumangalam",
        "Woraiyur",
        "Lalgudi",
        "Musiri",
        "Mannargudi",
        "Karur",
        "Perambalur",
        "Ariyalur",
        "Thanjavur",
        "Pudukkottai",
    ],
    Erode: [
        "Erode City",
        "Bhavani",
        "Perundurai",
        "Gobichettipalayam",
        "Sathyamangalam",
        "Chennimalai",
        "Kodumudi",
        "Modakurichi",
        "Bhavani Sagar",
        "Anthiyur",
        "Modakurichi Taluk",
        "Erode North",
        "Erode South",
    ],
    Tirunelveli: [
        "Tirunelveli City",
        "Nagercoil",
        "Shenkottai",
        "Tenkasi",
        "Ambasamudram",
        "Radhapuram",
        "Kovilpatti",
        "Sankarankovil",
        "Srivilliputhur",
        "Tuticorin",
        "Tirunelveli North",
        "Tirunelveli South",
        "Tirunelveli East",
        "Tirunelveli West"
    ],
    Vellore: [
        "Vellore City",
        "Tiruvannamalai",
        "Katpadi",
        "Vaniyambadi",
        "Gudiyatham",
        "Arakkonam",
        "Kaveripakkam",
        "Ranipet",
        "Ambur",
        "Tirupattur",
        "Vellore North",
        "Vellore ",
    ],
    Thoothukudi: [
        "Thoothukudi City",
        "Tiruchendur",
        "Kovilpatti",
        "Srivaikuntam",
        "Tiruchendur",
        "Kadayanallur",
        "Sattur",
        "Alangulam",
        "Tiruvarur",
        "Nagapattinam"
    ],
};

module.exports = { cities, cityAreas };

